#!/bin/bash

# Script that will detect whether or not  munkireport-php is installed and install Munki Time Window accordingly
# Intended to be used with munkipkg (https://github.com/munki/munki-pkg) as a pkg postinstall script
# Assumes that MunkiTimeWindow.py is a payload that installs to /usr/local/munki

# If /usr/local/munki/preflight_abort.d directory exists (MunkiReport installed)
if [ -d /usr/local/munki/preflight_abort.d/ ]
then
# Move MunkiTimeWindow.py inside preflight_abort.d
	mv /usr/local/munki/MunkiTimeWindow.py /usr/local/munki/preflight_abort.d/MunkiTimeWindow.py
else
# Rename MunkiTimeWindow.py to preflight (so that Munki will use it directly)
	mv /usr/local/munki/MunkiTimeWindow.py /usr/local/munki/preflight
fi
